spring:
  application:
    name: danuri-rest

  output:
    ansi:
      enabled: ALWAYS

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8081

sentry:
  dsn: "${SENTRY_DSN}"
  exception-resolver-order: -2147483647
  max-request-body-size: always
  send-default-pii: true
  traces-sample-rate: 1.0

discord:
  name: discord-feign-client
  webhook-url: ${DISCORD_WEBHOOK}

sms:
  apiKey: ${SMS_API_KEY}
  apiSecret: ${SMS_SECRET_KEY}
  fromnumber: ${SMS_FROM_NUMBER}

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  access-token-key: ${ACCESS_TOKEN_KEY}
  refresh-token-key: ${REFRESH_TOKEN_KEY}
  access-token-expires: 26297460000 # 10 month
  refresh-token-expires: 315569520000 # 10 years

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  access-token-key: ${ACCESS_TOKEN_KEY}
  refresh-token-key: ${REFRESH_TOKEN_KEY}
  access-token-expires: 1800000 # 30 minutes
  refresh-token-expires: 4320000000 # 1 day