spring:
  application:
    name: danuri-rest

  output:
    ansi:
      enabled: ALWAYS

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

ACCESS_EXPIRE_TIME: 26297460000 #10?
REFRESH_EXPIRE_TIME: 315569520000 #10?

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate

ACCESS_EXPIRE_TIME: 1800000 # 30?
REFRESH_EXPIRE_TIME: 8640000000 # 100?