name: GHCR Image Cleanup

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  cleanup:
    name: Cleanup old GHCR images
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Run GHCR Cleanup Action
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          keep-n-tagged: 5
          exclude-tags: master,develop
          delete-untagged: true
          keep-n-untagged: 0
          older-than: 14 days
          delete-ghost-images: true
          delete-partial-images: true
          delete-orphaned-images: true
          dry-run: false
